### ISSUE TITLE
Markers for projects that support .NET Core?

### ISSUE THREAD

**Issue by rogersachan** [quozd/awesome-dotnet#317]
Hi,

I would like to suggest some sort of marker for projects that have current support for asp.net core. 

As many projects are in the early stages of adding support, there might be a need for two markers to distinguish between full support and beta support.

Thoughts?

_@pleb edited to add missing body_

**Comment by pleb** [comment]
I think it's a good idea. My only concern would be bring the current list items up to date

**Comment by rogersachan** [comment]
@pleb Markers for support of .NET Core Console would be welcome too.

**Comment by pleb** [comment]
:thought_balloon: I guess it should simply be .net core

**Comment by pleb** [comment]
@rogersachan thoughts about 650dc8d?

**Comment by rogersachan** [comment]
Definitely what I meant, and seems to cover both ground on marking which supports what out.

**Comment by pleb** [comment]
@quozd @vladen @Jeffiy @devkhan - your chance to have input on this

**Comment by devkhan** [comment]
"Partial Support" instead of "beta support" might be a better term.

Also, is it possible to automate this? For example, by visiting the project pages using GitHub's API and parsing the README for nuget links and then using the nuget API to check if the package exists for `.NET Standard` moniker. This won't cover all projects but many of them and plus, we can add a CI check to automatically do this for every PR in future.

**Comment by Jogai** [comment]
https://github.com/Awesome-Windows/Awesome does something similar with icons. I think it would be even easier if the icons are in front of an entry, that way you can quickly scan trough the list without adjusting your eyes in the horizontal direction.

**Comment by quozd** [comment]
Icons 👍

**Comment by pleb** [comment]
Yep Icons seems like an elegant way to address this

**Comment by EricJFisher** [comment]
I would also venture to say we consider .NET Core as "supported" only if it works with 1.0+ there were libraries that were updated to work with RC1 and RC2 that don't work with Core 1.0.

**Comment by pleb** [comment]
Ok, so I guess all we need now is a suit of icons. Anybody handy with making icons?

**Comment by Jogai** [comment]
Icons by Mike Rowe:
.net: https://thenounproject.com/itsmikerowe/icon/74711/
core: https://thenounproject.com/itsmikerowe/icon/75368/ (cause you can use atom-like editors (vscode))

free: https://thenounproject.com/itsmikerowe/icon/384006/
paid but free for oss: https://thenounproject.com/itsmikerowe/icon/394845/
paid but oss itself: https://thenounproject.com/itsmikerowe/icon/394839/
proprietary: https://thenounproject.com/itsmikerowe/icon/384012/
paid & proprietary: https://thenounproject.com/itsmikerowe/icon/394837/

**Comment by atrauzzi** [comment]
I think as part of this, if a project is known to work in .net core via an imports entry, maybe it would be nice to include that as well.

Also, many projects don't have core support, but have open tickets for it. A link to those tickets should be provided in the same column when a library didn't have core support.

**Comment by zihotki** [comment]
So, as of now most of the projects (except very-very old and not very supported and Windows specific) do support .NET Core. Because of that it makes no sense to have any additional markers or something like that. For that reason I'm closing the issue but feel free to raise your opinion if you experience different situation and have other ideas.

**Comment by atrauzzi** [comment]
The close makes sense here, although it might be interesting to list supported TFMs in the index.
