### ISSUE TITLE
Second and smaller list

### ISSUE THREAD

**Issue by pleb** [quozd/awesome-dotnet#545]
There have been a few projects which haven't made it because they're either too small or possibly not awesome; with some projects almost making cringe when I hit close PR because I think they're pretty good. 

I'm wondering if adding a second list for new or small projects would be a good idea?

**Comment by atifaziz** [comment]
@pleb I think it would be more interesting to come up with labels to tag PRs that get closed without being merged. Example of labels could be “too-small”, “too-new”, “not-awesome” or whatever your criteria might be for a PR not making the cut. The lists would then just create themselves by filtering issues on labels. You could also use a label like “too-new” to return to return to projects periodically that may have aged/matured. Just an idea.

**Comment by SlowLogicBoy** [comment]
@pleb that would help small projects to get community recognition and get feedback, that way they will be able to get to this list faster.

**Comment by Entomy** [comment]
Is there any progress on this at all? While I understand not accepting a project because it's "not-awesome", size doesn't make much sense. Sometimes something is small because of a relative niche purpose. Sometimes projects have tens of thousands of package downloads on Nuget but only a few project stars on the repo. And I gotta agree with another comment: it helps smaller projects get recognition and helps people find them. Helping massive projects get even more attention keeps everything exactly as is, despite any progress people have made.
