### ISSUE TITLE
Community rank markers

### ISSUE THREAD

**Issue by wachulski** [quozd/awesome-dotnet#600]
Consider e.g. nuget download badges (https://shields.io/ to search for inspiration) to help people know how popular/used/renowned libs or tools are out there.

**Comment by SlowLogicBoy** [comment]
Good idea.
But many projects are supporting few versions simultaneously, how to act in those cases? Some projects don't support nuget, or support nuget and myget etc.. :)

**Comment by zihotki** [comment]
Similar idea was shared by others some time ago but unfortunately there is no single good metric to show how popular/used lib or tool is since not all of them are on github and opensource. Also I'm afraid that adding those labels will cause multiple issues - we'll need either to update them from time to time or implement dynamic loading which will lead to hundred of requests to load the numbers, that'd kill the page. And that'll add a plenty of visual noise which is irrelevant for a user looking for some library. If user looks for some library he already has a problem to solve and he can identify the problem area, find suitable section and open a few suitable libraries to do further research/exploration. Number of downloads and popularity is sort of irrelevant in this scenario, all the relevant and up to date numbers he'll see on the pages he opens. This is one-time task so the clicks user need to do can be easily justified. 
My opinion is that current list is good enough since it requires minimal maintenance with low effort, allows to find good projects/libraries/tools.

**Comment by wachulski** [comment]
I understand. I agree that having each item decorated with badges will lead to enourmous noise and introduces issues. 

At the same time it might be worthwhile to indicate just top 3 with badges to inform people which ones are the most used in the industry. I entered the page just for curiosity and didn't have any problem to solve. Yet I wanted to see which are the most popular within their catetories just to remember their names for the future reference.

Just an 💡

**Comment by pleb** [comment]
Too hard basket?

**Comment by zihotki** [comment]
I'm closing it because there was no active discussion of the topic and the idea seems to be too hard to implement and even harder to maintain.
